//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Adobe Connect SDK")]
[assembly: System.Reflection.AssemblyProduct("Adobe Connect SDK")]
[assembly: System.Reflection.AssemblyDescription(".Net wrapper for Adobe Connect Professional web services.")]
[assembly: System.Reflection.AssemblyVersion("2.3.2019")]
[assembly: System.Reflection.AssemblyFileVersion("2.3.2019")]
